# Generated by Django 3.2.9 on 2021-11-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='foodoffer',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.option'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.adress'),
        ),
    ]
