# Generated by Django 3.2.9 on 2021-11-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod', to='backend.productimage'),
        ),
    ]
