# Generated by Django 3.2.9 on 2021-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
