# Generated by Django 3.2.9 on 2021-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_product_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
