# Generated by Django 3.2.9 on 2021-12-16 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0011_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
