# Generated by Django 3.2.9 on 2021-12-16 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_restaurant_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owners',
            field=models.ManyToManyField(related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
