# Generated by Django 3.2.9 on 2021-12-16 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0013_alter_restaurant_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owners',
            field=models.ManyToManyField(help_text='users who possess the restaurant', related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(related_name='restaurants', to='backend.Tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(help_text='totla reviews score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='total_reviews',
            field=models.IntegerField(help_text='totale score'),
        ),
    ]
